
PYTHON               ?= python
KICAD_PCB_TO_SCAD_PY  = ../../../Shared/3D/kicad_pcb_to_scad.py
MAINBOARD_KICAD_PCB   = ../../PCB/Mainboard/Mainboard.kicad_pcb
SUBBOARDS_KICAD_PCB   = ../../PCB/Subboards/Subboards.kicad_pcb

.PHONY: all
all:

include $(wildcard */build.mk)

